export const Video = [
  {
    "Title": "What is Pro Presenter?",
    "Tag": "Getting Started",
    "Url": "https://www.youtube.com/embed/m1LdbRmJsQI",
    "Description": "<div>\n  <p>Discover the wonders of Pro Presenter, your key to creating stunning presentations for any music event. Whether you're new to this or a seasoned pro, Pro Presenter makes it easy to dazzle your audience.</p>\n\n  <h3>Create Awesome Presentations:</h3>\n\n  <p>With Pro Presenter, you can make eye-catching presentations that keep your audience hooked. Even if you're not a tech expert, you'll be able to make your show look amazing.</p>\n\n  <h3>Show on Multiple Screens:</h3>\n\n  <p>Share your presentation on different screens at once. No matter where people are watching - on stage, in the crowd, or on a screen - everyone gets to enjoy the show up close.</p>\n\n  <h3>Control How the Story Unfolds:</h3>\n\n  <p>Take charge of your show's story using Pro Presenter. You can control it from a computer, a special device, or even your phone. It's like being the director of your own music production.</p>\n\n  <h3>Add Exciting Videos:</h3>\n\n  <p>Make your show even cooler by adding videos alongside your presentation. You can stream videos to make your performance more dynamic and captivating.</p>\n\n  <h3>Big or Small, It Fits All:</h3>\n\n  <p>Whether you're performing in a cozy space or a huge venue, Pro Presenter is perfect. It adapts to what you need and helps you shine, no matter the size of your event.</p>\n\n  <h3>Your Partner in Production:</h3>\n\n  <p>Step into the world of Pro Presenter, your all-in-one tool for creating fantastic live music experiences. With Pro Presenter, you're in control, and your shows will leave a lasting impression.</p>\n\n  <h3>Stay Tuned for More:</h3>\n\n  <p>Keep an eye on our channel for more tips and tricks with Pro Presenter. We'll help you unlock all the amazing things it can do, so you can create performances that truly stand out.</p>\n</div>"
  }
  ,
  {
    "Title": "Configure Screens in Pro Presenter",
    "Tag": "Getting Started",
    "Url": "https://www.youtube.com/embed/ROOFKBbvNns",
    "Description": "<div>\n  <p>Explore the magic of ProPresenter Under 7 and take control of your screen setup effortlessly. Whether you're new to this or just want a smoother process, ProPresenter makes configuring screens a breeze.</p>\n\n  <h3>Setting Up Your Screens:</h3>\n\n  <p>With ProPresenter, you can arrange and manage your screens with ease. Connect as many screens as your computer can handle, from physical displays to network screens. You'll be guided through a simple process to configure them and set them up in advance.</p>\n\n  <h3>Audience and Stage Screens:</h3>\n\n  <p>ProPresenter lets you create different screens for your audience and stage. Audience screens are for the crowd, while stage screens are for those on stage or behind the scenes. You can even have multiple screens for each category.</p>\n\n  <h3>Customize Your Screens:</h3>\n\n  <p>Personalize your screens by naming and adjusting them. Choose your output devices and even configure placeholders for screens you haven't connected yet.</p>\n\n  <h3>Flexible Output Options:</h3>\n\n  <p>ProPresenter supports various output sources, including NDI and Syphon, allowing you to send video across networks or to other programs on your computer. You can also adjust screen ratios and resolutions to fit your needs.</p>\n\n  <h3>Mirrored and Group Screens:</h3>\n\n  <p>Enhance your visual impact by using mirrored screens to send the same output to multiple destinations. Create impressive video walls or ultra-wide setups with group screens, perfect for video walls or wide displays.</p>\n\n  <h3>Edge Blending:</h3>\n\n  <p>Master the art of edge blending for seamless screen transitions. Adjust the blend between screens and create stunning visual effects that captivate your audience.</p>\n\n  <h3>Stage Display Setup:</h3>\n\n  <p>Configure multiple stage displays for those on stage. ProPresenter lets you set up physically connected screens or use NDI or Syphon outputs. You can even view stage screen layouts from the iOS and Android Stage app.</p>\n\n  <h3>Next-Level Control:</h3>\n\n  <p>Unlock the full potential of your presentation with ProPresenter's features. Send different content and looks to various screens using the new announcements layer and looks features.</p>\n\n  <h3>More Tutorials:</h3>\n\n  <p>Stay tuned for additional tutorials on ProPresenter's advanced features, including the announcements layer, looks, image splitters, and edge blending. Visit renewedvision.com/ProTutorial for detailed guides.</p>\n</div>"
  },
  {
    "Title": "Importing New Songs into Pro Presenter",
    "Tag": "Getting Started",
    "Url": "https://www.youtube.com/embed/AWCt0eVG6bg",
    "Description": "<div>\n  <p>Ready to simplify importing lyrics and chord charts for your presentations in ProPresenter? In this tutorial, we'll guide you through the easy steps of using the Multi-Track Search feature and displaying chord charts on your stage screens.</p>\n\n  <h3>Importing Lyrics and Chord Charts:</h3>\n\n  <p>With ProPresenter, you can quickly import lyrics and chord charts for your songs. To start, you'll need a Chart Pro subscription from multitracks.com. This subscription provides access to digital chord sheets that you can print and import. Plus, it allows you to search and import songs directly into ProPresenter.</p>\n\n  <h3>Connecting Your Accounts:</h3>\n\n  <p>Log into your multitracks.com account within ProPresenter's preferences. This connection enables you to easily search and import songs from the multitracks database directly into ProPresenter.</p>\n\n  <h3>Searching for Songs:</h3>\n\n  <p>Use the Multi-Track Search feature to find your desired songs. Type in the song name, like 'Christ be Magnified,' and choose your preferred version. You'll get helpful details about the song, including key and chord chart availability.</p>\n\n  <h3>Importing Chord Charts:</h3>\n\n  <p>Importing is a breeze! Choose your options, such as bringing in chords and automation. Adjust the key if needed, select the number of lines per slide, and apply a theme. Then, import the song, and it's ready to go.</p>\n\n  <h3>Create an Arrangement:</h3>\n\n  <p>ProPresenter offers pre-built arrangements or the flexibility to create your own. Easily set up your song arrangement for smooth presentations.</p>\n\n  <h3>Displaying Chord Charts on Stage:</h3>\n\n  <p>Enhance your stage screens by adding a new stage layout. Choose the Multi-Track Chords and Lyrics pre-built layout, and adjust settings like chord colors and text appearance. You can even switch between different keys effortlessly.</p>\n\n  <h3>Applying the Layout:</h3>\n\n  <p>Activate your new layout for your stage screens. Preview and adjust as needed to ensure your musicians have clear chord charts displayed above the lyrics, matching your chosen key.</p>\n\n  <h3>Conclusion:</h3>\n\n  <p>With Multi-Track Search and Chord Chart features, ProPresenter streamlines the process of importing songs and displaying accurate chord charts. Visit multitracks.com to learn more and subscribe, and take your presentations to the next level!</p>\n</div>"
  },
  {
    "Title": "Connecting Planning Center to Pro presenter",
    "Tag": "Getting Started",
    "Url": "",
    "Description": "<div class=\"article-body\">\n<p><strong>Connecting Planning Center Services to ProPresenter</strong></p>\n\n<p>Planning Center Services is a third-party service that can be integrated with ProPresenter for seamless functionality. To set it up, follow these steps:</p>\n\n<p><strong>Step 1: Open ProPresenter Preferences</strong></p>\n\n<p>In ProPresenter, navigate to <strong>Preferences</strong> and click on the <strong>Services</strong> tab.</p>\n\n\n<p><strong>Step 2: Login to Planning Center</strong></p>\n\n<p>Click the <strong>Login</strong> button next to <strong>Planning Center Online</strong>.</p>\n</p>\n\n<p>Enter your account information in the login window and select your organization on the next screen. If you're a member of only one organization, you'll be signed in immediately.</p>\n\n<p><strong>Step 3: Authorize ProPresenter</strong></p>\n\n<p>The first time you connect to Planning Center, you'll need to authorize ProPresenter to access your account. Click <strong>Allow</strong>.</p>\n\n\n<p><strong>Step 4: Confirmation</strong></p>\n\n<p>Once you've successfully logged into your Planning Center Services account through ProPresenter, you'll see your name and organization name displayed in ProPresenter's Preferences.</p>\n\n<p>We recommend using an Editor or Administrator account from your Planning Center plan for the integration.</p>\n\n<p>That's it! You've successfully connected ProPresenter to your Planning Center account.</p>\n\n</div>"
  },
  {
    "Title": "Importing Planning Center Plan to Pro Presenter",
    "Tag": "Getting Started",
    "Url": "",
    "Description": "<div class=\"article-body\">\n<p><strong>Adding a Planning Center Plan to ProPresenter</strong></p>\n\n<p>In this guide, we will walk you through the process of adding a Planning Center Plan to ProPresenter. We will also explore various preference settings to help you better understand their functionalities.</p>\n\n<p><strong>Prerequisites:</strong> Familiarity with using Planning Center Services is assumed.</p>\n\n<p><strong>Step 1: Add Planning Center Plan</strong></p>\n\n<p>Start by clicking the <strong>+</strong> (plus sign) next to <strong>Library</strong>, then select <strong>Planning Center Service</strong> from the menu.</p>\n\n<p>This opens a window displaying your available Plans. The option to <strong>Show Historical Service Plans</strong> affects which Plans are shown. Choose a Plan and click <strong>Select</strong> to add it as a playlist in ProPresenter.</p>\n\n\n<p><strong>Step 2: Link Songs in Library</strong></p>\n\n<p>When a Planning Center song is linked to a ProPresenter presentation, it appears as a normal presentation with a second title bar. This bar contains the Planning Center item name and provides the option to unlink a presentation.</p>\n\n\n<p>If a song is not linked, it shows a drop area. You can link a presentation from the library, a media file, or cancel the drop zone if it's just a placeholder.</p>\n\n<p>To link an existing presentation to a Planning Center item, use the Search function to locate the presentation, then drag and drop it into the drop zone.</p>\n\n<p><strong>Step 3: Matching and Complex Plans</strong></p>\n\n<p>If a Planning Center song matches a ProPresenter presentation, it will appear in the playlist as usual. Headers in Planning Center serve the same purpose as those in ProPresenter but cannot be edited. Headers organize the order.</p>\n\n<p>More complex Plans can be synchronized to ProPresenter using the <strong>Automatically Check for Plan Updates</strong> setting. Items without a matching ProPresenter counterpart can be linked manually.</p>\n\n<p><strong>Step 4: Convert to Standard Playlist</strong></p>\n\n<p>To gain more control over the playlist content and manipulate headers, right-click on a Planning Center Plan and select <strong>Convert to Standard Playlist</strong>.</p>\n\n</div>"
  }
  ,
  {
    "Title": "Connecting Playback to Pro Presenter",
    "Tag": "Advanced",
    "Url": "https://www.youtube.com/embed/oB7dmAEAphE",
    "Description": "<div>\n\
      <p>Welcome to the first video in our series on controlling ProPresenter using MIDI out from playback. I'm Christian from multi-tracks.com, and in this tutorial, we'll guide you through the process of establishing the connection between your computer running ProPresenter and your iOS device running Playback.</p>\n\n\
      <p>There are various ways to physically establish this connection. You can achieve this over Wi-Fi, through an Ethernet cable using the Lightning to Ethernet adapter on your iOS device, or via an audio interface with an Ethernet port, like the IEEE Connectivity Play Audio 12. For today, we'll focus on Wi-Fi and Ethernet methods.</p>\n\n\
      <p>Once you've set up the connection between your devices, whether through Ethernet or Wi-Fi, it's time to establish the MIDI connection between them. Let's get started by using the 'Audio MIDI Setup' app on your Mac. This app is available on every Mac computer.</p>\n\n\
      <p>If you can't see the 'MIDI Studio' window, you can access it by going to 'Window' and selecting 'Show MIDI Studio.' In this window, you'll find the 'Network' section. On newer versions of macOS, click the globe icon to configure the Network driver. Let's proceed with creating a MIDI session.</p>\n\n\
      <p>Click the '+' sign to create a session and give it a name. In this example, we'll call it 'Playback MIDI Session.' The entry box below will list available devices to connect to this MIDI network. To see all computers on the network, make sure you select 'Any Computer.'</p>\n\n\
      <p>Now, on your iPad running Playback or a similar MIDI-sending app, open the app to establish the connection. Once your device appears in the 'Participants' section, click 'Connect.' This action establishes the MIDI connection between your devices, enabling MIDI communication.</p>\n\n\
      <p>If you're using an Ethernet connection via an iconic tivity device, you'll see the available ports on your device listed instead of your iPad's name. Connect to the appropriate port for your setup.</p>\n\n\
      <p>With the network and MIDI connection established, you're ready to proceed inside the apps to configure and use the MIDI functionalities for seamless communication between ProPresenter and Playback.</p>\n\
      </div>"
  },
  {
    "Title": "Setting Up MIDI for ProPresenter",
    "Tag": "Advanced",
    "Url": "https://www.youtube.com/embed/KuV2ze2Yr0k",
    "Description": ""
  } 

]
